server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Logs Docker containers
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*))\|(?P<image_tag>(?:[^|]*))
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
          image_tag:
      - output:
          source: output

  # Logs applicatifs JSON
  - job_name: artfans_api
    static_configs:
      - targets:
          - localhost
        labels:
          job: artfans_api
          __path__: /logs/artfans-api.log
    
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            type: type
            event: event
            user_id: user_id
            error: error
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          type:
          event:
      - output:
          source: message