global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'go-backend'
    static_configs:
      - targets: ['api:8080']
        labels:
          service: 'artfans-api'
          
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
        labels:
          service: 'loki'