apiVersion: apps/v1
kind: Deployment
metadata:
  name: artfans-api
  namespace: artfans
  labels:
    app: artfans-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: artfans-api
  template:
    metadata:
      labels:
        app: artfans-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000

      volumes:
        - name: cloudsql-creds
          secret:
            secretName: gcs-credentials

      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.2
          env:
            - name: CLOUD_SQL_CONNECTION_NAME
              value: "artfans-68ff4:europe-west1:artfans-pg"
          command:
            - "/cloud_sql_proxy"
            - "-instances=$(CLOUD_SQL_CONNECTION_NAME)=tcp:5432"
            - "-credential_file=/secrets/key.json"
          volumeMounts:
            - name: cloudsql-creds
              mountPath: /secrets
              readOnly: true

        - name: api
          image: europe-docker.pkg.dev/artfans-68ff4/artfans/artfans-api:v1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: "postgres://artfans:artfans_pass@127.0.0.1:5432/artfans_dev?sslmode=disable"
            - name: GCS_BUCKET
              value: "artfans-uploads"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
