apiVersion: apps/v1
kind: Deployment
metadata:
  name: artfans-api
  namespace: artfans
spec:
  replicas: 2
  selector:
    matchLabels:
      app: artfans-api
  template:
    metadata:
      labels:
        app: artfans-api
    spec:
      serviceAccountName: default
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        # Container principal API
        - name: api
          image: europe-docker.pkg.dev/PROJECT_ID/artfans/artfans-api:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: artfans-backend-secrets
          env:
            - name: POSTGRES_HOST
              value: "127.0.0.1"
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          volumeMounts:
            - name: uploads
              mountPath: /uploads
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        
        # Sidecar Cloud SQL Proxy
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
          args:
            - "--structured-logs"
            - "--port=5432"
            - "$(INSTANCE_CONNECTION_NAME)"
          env:
            - name: INSTANCE_CONNECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: artfans-backend-secrets
                  key: INSTANCE_CONNECTION_NAME
          securityContext:
            runAsNonRoot: true
            runAsUser: 2000
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
      
      volumes:
        - name: uploads
          emptyDir: {}