apiVersion: apps/v1
kind: Deployment
metadata:
  name: artfans-api
  namespace: artfans
spec:
  replicas: 2
  selector:
    matchLabels:
      app: artfans-api
  template:
    metadata:
      labels:
        app: artfans-api
    spec:
      serviceAccountName: cloudsql-proxy
      containers:
      - name: api
        image: europe-docker.pkg.dev/pure-karma-466322-v8/artfans/artfans-api:fixed-v3
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: artfans-backend-secrets
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 20
        volumeMounts:
        - name: uploads
          mountPath: /uploads
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
        args:
        - "--port=5432"
        - "pure-karma-466322-v8:europe-west9:artfans-pg"
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc