apiVersion: apps/v1
kind: Deployment
metadata:
  name: artfans-api
  namespace: artfans
spec:
  replicas: 2
  selector:
    matchLabels:
      app: artfans-api
  template:
    metadata:
      labels:
        app: artfans-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: api
        image: europe-docker.pkg.dev/pure-karma-466322-v8/artfans/artfans-api:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: artfans-backend-secrets
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: uploads
          mountPath: /uploads
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - NET_BIND_SERVICE
            drop:
              - ALL
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
        args:
        - "--instance=pure-karma-466322-v8:europe-west9:artfans-pg"
        - "--port=5432"
        securityContext:
          runAsNonRoot: true
          runAsUser: 2
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc
