apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: artfans
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard