apiVersion: v1
kind: Service
metadata:
  name: artfans-api-service
  namespace: artfans
spec:
  selector:
    app: artfans-api
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: artfans-web-service
  namespace: artfans
spec:
  selector:
    app: artfans-web
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: LoadBalancer