apiVersion: v1
kind: Service
metadata:
  name: artfans-api
  namespace: artfans
spec:
  type: ClusterIP
  selector:
    app: artfans-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
