apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: artfans
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
