apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: artfans
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  _;
        
        root /usr/share/nginx/html;
        index index.html;
        
        # Proxy API calls to backend
        location /api {
            proxy_pass http://artfans-api-service:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }
        
        # Health check
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
        
        # Flutter web app - try files then fallback to index
        location / {
            try_files $uri $uri/ /index.html;
        }
        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }