apiVersion: v1
kind: Service
metadata:
  name: artfans-web
  namespace: artfans
spec:
  type: ClusterIP
  selector:
    app: artfans-web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
