apiVersion: v1
kind: Secret
metadata:
  name: artfans-backend-secrets
  namespace: artfans
type: Opaque
stringData:
  POSTGRES_USER: artfans
  POSTGRES_PASSWORD: artfans_pass
  POSTGRES_DB: artfans_dev
  DATABASE_URL: postgres://artfans:artfans_pass@postgres:5432/artfans_dev?sslmode=disable
  JWT_SECRET: une_clef_secrete
  STRIPE_KEY: sk_test_xxx
