name: docker-ssh-cd

on:
  workflow_run:
    workflows: ["CI ARTFANS"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
      - name: Deploy
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOS'
            set -e
            cd /opt/artfans

            if [ -d .git ]; then
              git pull origin main
            else
              git clone https://github.com/${{ github.repository }} .
            fi

            docker compose pull         # seulement postgres
            docker compose build        # reconstruit api + app
            docker compose up -d --remove-orphans
            docker image prune -f
          EOS
