name: CI ARTFANS

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:

  lint-and-test:
    name: Lint & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache Flutter Pub
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('frontend/pubspec.yaml') }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - name: Install Flutter dependencies
        working-directory: frontend
        run: flutter pub get
      - name: Dart analyze
        working-directory: frontend
        run: flutter analyze
      - name: Flutter unit tests
        working-directory: frontend
        run: flutter test --coverage

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}
      - name: Go fmt & vet
        working-directory: backend
        run: |
          go fmt ./...
          go vet ./...
      - name: Go unit tests
        working-directory: backend
        run: go test ./... -coverprofile=coverage.out

  integration:
    name: Integration Tests
    needs: lint-and-test
    runs-on: ubuntu-latest
    services:
      backend:
        image: golang:1.21
        options: >-
          --health-cmd="go test ./... -timeout 30s"
          --health-interval=10s
        ports:
          - 8080:8080
      chrome:
        image: selenium/standalone-chrome:latest
        options: >-
          --shm-size=2gb
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build & Run backend
        working-directory: backend
        run: |
          go build -o app main.go
          ./app &

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - name: Install Flutter dependencies
        working-directory: frontend
        run: flutter pub get
      - name: Run integration tests on Web
        working-directory: frontend
        run: flutter test integration_test/app_test.dart --platform chrome

  build-and-upload:
    name: Build & Upload Artifacts
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - name: Build Android APK
        working-directory: frontend
        run: flutter build apk --release
      - name: Build Web bundle
        working-directory: frontend
        run: flutter build web --release

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build Go binary
        working-directory: backend
        run: |
          go build -o bin/artfans-server main.go

      - name: Upload Flutter APK
        uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: frontend/build/app/outputs/flutter-apk/app-release.apk
      - name: Upload Flutter Web
        uses: actions/upload-artifact@v3
        with:
          name: flutter-web
          path: frontend/build/web
      - name: Upload Go Binary
        uses: actions/upload-artifact@v3
        with:
          name: go-binary
          path: backend/bin/artfans-server
