name: CI ARTFANS

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  go-check:
    name: Go Lint & Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/richard-lam-webdev/artfans-ci:amd64
    steps:
      - uses: actions/checkout@v3
      - name: Go fmt & vet
        working-directory: backend
        run: |
          go fmt ./...
          go vet ./...
      - name: Go unit tests
        working-directory: backend
        run: go test ./... -coverprofile=coverage.out

  flutter-analyze:
    name: Flutter Analyze
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/richard-lam-webdev/artfans-ci:amd64
    steps:
      - uses: actions/checkout@v3
      - name: Dart analyze
        working-directory: frontend
        run: flutter analyze

  flutter-integration:
    name: Flutter Integration Tests
    needs: flutter-analyze
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/richard-lam-webdev/artfans-ci:amd64
    steps:
      - uses: actions/checkout@v3
      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1920x1080x24 &
        env:
          DISPLAY: :99
      - name: Run integration tests on Web
        working-directory: frontend
        env:
          DISPLAY: :99
        run: flutter drive \
               --driver=test_driver/integration_test.dart \
               --target=integration_test/app_test.dart \
               -d web-server

  build-and-upload:
    name: Build & Upload Artifacts
    needs: [ go-check, flutter-analyze, flutter-integration ]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/richard-lam-webdev/artfans-ci:amd64
    steps:
      - uses: actions/checkout@v3
      - name: Build Android APK
        working-directory: frontend
        run: flutter build apk --release
      - name: Build Web bundle
        working-directory: frontend
        run: flutter build web --release
      - name: Build Go binary
        working-directory: backend
        run: go build -o bin/artfans-server ./cmd/server
      - name: Upload Flutter APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: frontend/build/app/outputs/flutter-apk/app-release.apk
      - name: Upload Flutter Web
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web
          path: frontend/build/web
      - name: Upload Go Binary
        uses: actions/upload-artifact@v4
        with:
          name: go-binary
          path: backend/bin/artfans-server
