name: CI ARTFANS

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # 1) Go Lint & Tests
  go-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with: { go-version: '1.21' }
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}
      - name: Go fmt & vet
        working-directory: backend
        run: |
          go fmt ./...
          go vet ./...
      - name: Go unit tests
        working-directory: backend
        run: go test ./... -coverprofile=coverage.out

  # 2) Flutter Analyze
  flutter-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Flutter Pub
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-pub-${{ hashFiles('frontend/pubspec.yaml') }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with: { flutter-version: '3.29.2' }
      - name: Install Flutter dependencies
        working-directory: frontend
        run: flutter pub get
      - name: Dart analyze
        working-directory: frontend
        run: flutter analyze

  # 3) Flutter Integration Tests
  flutter-integration:
    name: Flutter Integration Tests
    needs: flutter-analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # → Cache et setup Flutter
      - name: Cache Flutter Pub
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-pub-${{ hashFiles('frontend/pubspec.yaml') }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install Flutter dependencies
        working-directory: frontend
        run: flutter pub get

      # → Installer Chromium & Xvfb pour émuler un display
      - name: Install Chromium & Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser xvfb

      - name: Start Xvfb on :99
        run: Xvfb :99 -screen 0 1920x1080x24 &
        env:
          DISPLAY: :99

      # → Lancer les tests d’intégration en mode web
      - name: Run integration tests on Web
        working-directory: frontend
        env:
          DISPLAY: :99
        run: |
          flutter drive \
            --driver=test_driver/integration_test.dart \
            --target=integration_test/app_test.dart \
            -d chrome


  # 4) Build & Upload Artifacts
  build-and-upload:
    name: Build & Upload Artifacts
    needs: [ go-check, flutter-analyze, flutter-integration ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Flutter build
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with: { flutter-version: '3.29.2' }
      - name: Build Android APK
        working-directory: frontend
        run: flutter build apk --release
      - name: Build Web bundle
        working-directory: frontend
        run: flutter build web --release

      # Go build
      - name: Setup Go
        uses: actions/setup-go@v4
        with: { go-version: '1.21' }
      - name: Build Go binary
        working-directory: backend
        run: go build -o bin/artfans-server ./cmd/server

      # Upload artifacts
      - name: Upload Flutter APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: frontend/build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Flutter Web
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web
          path: frontend/build/web

      - name: Upload Go Binary
        uses: actions/upload-artifact@v4
        with:
          name: go-binary
          path: backend/bin/artfans-server
